#!/bin/sh

set -e

[ -x /usr/local/bin/docker-run-pre ] && /usr/local/bin/docker-run-pre

docker-bootstrap

if [ -x /usr/local/bin/docker-run-alt ]; then
	exec /usr/local/bin/docker-run-alt
else
	exec su-exec minidlna minidlnad -f /conf.d/minidlna/minidlna.conf -S
fi

